// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDatabasePath() {
  return window['go']['services']['DatabaseFileService']['GetCurrentDatabasePath']();
}

export function OpenDatabase() {
  return window['go']['services']['DatabaseFileService']['OpenDatabase']();
}

export function OpenGuides() {
  return window['go']['services']['DatabaseFileService']['OpenGuides']();
}

export function SaveDatabaseAs() {
  return window['go']['services']['DatabaseFileService']['SaveDatabaseAs']();
}
