// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDatabasePath():Promise<string>;

export function HasUnsavedChanges():Promise<boolean>;

export function IsMemoryDatabase():Promise<boolean>;

export function OpenDatabase():Promise<string>;

export function OpenGuides():Promise<void>;

export function SaveDatabaseAs():Promise<string>;
