// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClients(arg1) {
  return window['go']['main']['App']['GetClients'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}
