// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateHumanResource(arg1) {
  return window['go']['main']['App']['CreateHumanResource'](arg1);
}

export function CreateMilestone(arg1) {
  return window['go']['main']['App']['CreateMilestone'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProjectResource(arg1) {
  return window['go']['main']['App']['CreateProjectResource'](arg1);
}

export function CreateProjectRole(arg1) {
  return window['go']['main']['App']['CreateProjectRole'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteHumanResource(arg1) {
  return window['go']['main']['App']['DeleteHumanResource'](arg1);
}

export function DeleteMilestone(arg1) {
  return window['go']['main']['App']['DeleteMilestone'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectResource(arg1) {
  return window['go']['main']['App']['DeleteProjectResource'](arg1);
}

export function DeleteProjectRole(arg1) {
  return window['go']['main']['App']['DeleteProjectRole'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetByProjectAndResource(arg1, arg2) {
  return window['go']['main']['App']['GetByProjectAndResource'](arg1, arg2);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClients(arg1) {
  return window['go']['main']['App']['GetClients'](arg1);
}

export function GetCurrentDatabasePath() {
  return window['go']['main']['App']['GetCurrentDatabasePath']();
}

export function GetHumanResource(arg1) {
  return window['go']['main']['App']['GetHumanResource'](arg1);
}

export function GetHumanResources(arg1) {
  return window['go']['main']['App']['GetHumanResources'](arg1);
}

export function GetMilestone(arg1) {
  return window['go']['main']['App']['GetMilestone'](arg1);
}

export function GetMilestones(arg1) {
  return window['go']['main']['App']['GetMilestones'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectResource(arg1) {
  return window['go']['main']['App']['GetProjectResource'](arg1);
}

export function GetProjectResources(arg1) {
  return window['go']['main']['App']['GetProjectResources'](arg1);
}

export function GetProjectRole(arg1) {
  return window['go']['main']['App']['GetProjectRole'](arg1);
}

export function GetProjectRoles(arg1) {
  return window['go']['main']['App']['GetProjectRoles'](arg1);
}

export function GetProjectRolesByProject(arg1) {
  return window['go']['main']['App']['GetProjectRolesByProject'](arg1);
}

export function GetProjects(arg1) {
  return window['go']['main']['App']['GetProjects'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function HasUnsavedChanges() {
  return window['go']['main']['App']['HasUnsavedChanges']();
}

export function IsMemoryDatabase() {
  return window['go']['main']['App']['IsMemoryDatabase']();
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function OpenGuides() {
  return window['go']['main']['App']['OpenGuides']();
}

export function SaveDatabaseAs() {
  return window['go']['main']['App']['SaveDatabaseAs']();
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateHumanResource(arg1) {
  return window['go']['main']['App']['UpdateHumanResource'](arg1);
}

export function UpdateMilestone(arg1) {
  return window['go']['main']['App']['UpdateMilestone'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectResource(arg1) {
  return window['go']['main']['App']['UpdateProjectResource'](arg1);
}

export function UpdateProjectRole(arg1) {
  return window['go']['main']['App']['UpdateProjectRole'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
